name: car_game
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1

  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4       # Optional: for authentication
  cloud_firestore: ^4.14.0     # Optional: for Firestore
  firebase_analytics: ^10.7.4  # Optional: for analytics

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.gif
    - assets/redcar.png
    - assets/start.png
    - assets/mountains.png
  fonts:
    - family: RaceFont
      fonts:
        - asset: assets/fonts/raceFont/SuperBrigade3D.otf
        - asset: assets/fonts/raceFont/SuperBrigadeItalic.otf
